parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.json
  tsconfigRootDir: ./
settings:
  react:
    pragma: React
    version: detect
  linkComponents:
    - name: Link
      linkAttribute: to
    - name: NavLink
      linkAttribute: to
env:
  browser: true
  es6: true
plugins:
  - react
  - react-hooks
  - "@typescript-eslint"
extends:
  - standard
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  array-bracket-spacing:
    - warn
    - never
  comma-dangle:
    - warn
    - always-multiline
  indent:
    - warn
    - tab
    - SwitchCase: 1
  no-tabs: 0
  multiline-ternary: 0
  semi:
    - warn
    - always
  space-before-function-paren: 0
  spaced-comment: 0
  quotes:
    - warn
    - single
  react/display-name:
    - warn
  react/prop-types:
    - warn
  react/jsx-indent-props:
    - warn
    - tab
  react/jsx-boolean-value:
    - warn
    - never
  react/jsx-closing-bracket-location:
    - 1
    - line-aligned
  react/jsx-closing-tag-location: 1
  react/react-in-jsx-scope: 0
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - warn
  "@typescript-eslint/ban-ts-comment": 0
  "@typescript-eslint/ban-ts-ignore": 0
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/explicit-member-accessibility": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/explicit-module-boundary-types":
    - warn
  # https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-use-before-define.md#how-to-use
  no-use-before-define: 0
  "@typescript-eslint/no-use-before-define":
    - warn
overrides:
  - files:
      - "**/*.tsx"
    rules:
      operator-linebreak:
        - error
        - before
        - overrides:
            "&&": "after"
            "?": "ignore"
            ":": "ignore"
